---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-whitelist-fly-io-v1alpha1-whitelist
  failurePolicy: Fail
  name: mwhitelist.kb.io
  rules:
  - apiGroups:
    - apps.whitelist.fly.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - whitelists
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-whitelist-fly-io-v1alpha1-whitelist
  failurePolicy: Fail
  name: vwhitelist.kb.io
  rules:
  - apiGroups:
    - apps.whitelist.fly.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - whitelists
  sideEffects: None
