apiVersion: apps.whitelist.fly.io/v1alpha1
kind: Whitelist
metadata:
  name: whitelist-sample-2
spec:
  # TODO(user): Add fields here
  provider: aliyun           
  service: rds  
  ipLevel: Pod 
  serviceId: "rm-bp1241tqaj3g303k1" 
  annotations:
    DBInstanceIPArrayName: test 
